# Generated by Django 5.2.18 on 2026-10-10 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_approvers_by_email(apps, schema_editor):
    """Approvers used to be matched to users by email; keep those matches as links."""
    Approver = apps.get_model("portfolios", "Approver")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    for approver in Approver.objects.filter(user__isnull=True).exclude(email=""):
        users = list(User.objects.filter(email__iexact=approver.email)[:2])
        if len(users) == 1:
            approver.user = users[0]
            approver.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The account this approver signs in with. Without it they cannot see requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approver',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='contact email'),
        ),
        migrations.RunPython(link_approvers_by_email, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='approver',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('portfolio', 'user'), name='unique_approver_user_per_portfolio'),
        ),
    ]
