# Generated by Django 5.2.18 on 2026-10-09 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('repository', 'Repository'), ('team', 'Team')], max_length=20)),
                ('target_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('modify', 'Modify'), ('archive', 'Archive')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='portfolios.portfolio')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('change', 'Change')], max_length=20)),
                ('principal_type', models.CharField(choices=[('team', 'Team'), ('user', 'User')], max_length=20)),
                ('principal_name', models.CharField(max_length=255)),
                ('old_permission', models.CharField(blank=True, max_length=20, null=True)),
                ('new_permission', models.CharField(blank=True, max_length=20, null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='change_requests.changerequest')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
